services:
  # ============================
  # SQL Server Database
  # ============================
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  # ============================
  # RabbitMQ
  # ============================
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "6672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

  # ============================
  # Asset Registry Service
  # ============================
  asset-registry:
    build:
      context: .
      dockerfile: src/Services/AssetRegistry/Dockerfile
    container_name: asset-registry
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__AssetRegistryDb: "Server=sqlserver,1433;Database=AssetRegistry;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=True;TrustServerCertificate=True"

      RabbitMq__Host: rabbitmq
      RabbitMq__Port: "5672"
      RabbitMq__UserName: guest
      RabbitMq__Password: guest

      OpenSearch__Enabled: "false"
      OpenSearch__Uri: "http://opensearch:9200"
      OpenSearch__Username: "admin"
      OpenSearch__Password: "admin"
      OpenSearch__IndexFormat: "asset-registry-logs-{0:yyyy.MM.dd}"
    depends_on:
      - rabbitmq
      - sqlserver
    restart: unless-stopped
    
  # ============================
  # Identity Access Service
  # ============================
  identity-access:
    build:
      context: .
      dockerfile: ./src/Services/IdentityAccess/DockerFile
    container_name: identity-access
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped

  # ============================
  # Maintenance Scheduler Service
  # ============================
  maintenance-scheduler:
    build:
      context: .
      dockerfile: ./src/Services/MaintenanceScheduler/Dockerfile
    container_name: maintenance-scheduler
    ports:
      - "5004:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MaintenanceSchedulerDB;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=True;TrustServerCertificate=True;MultipleActiveResultSets=true"
    depends_on:
      sqlserver:
        condition: service_healthy
    restart: unless-stopped

  # ============================
  # Notification Service
  # ============================
  notification:
    build:
      context: .
      dockerfile: src/Services/Notification/Dockerfile
    container_name: notification
    ports:
      - "5005:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped

  # ============================
  # Audit & Compliance Service
  # ============================
  audit-compliance:
    build:
      context: .
      dockerfile: /src/Services/AuditCompliance/Dockerfile
    container_name: audit-compliance
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped

  # ============================
  # Gateway / Load Balancer Service
  # ============================
  gateway:
    build:
      context: .
      dockerfile: src/Services/APIGateway/Dockerfile
    container_name: gateway
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - asset-registry
      - identity-access
      - maintenance-scheduler
      - notification
      - audit-compliance
    restart: unless-stopped

volumes:
  sqlserver-data:
    driver: local

networks:
  default:
    name: microservices-network
    driver: bridge